### ISSUE TITLE
Getting redirect_urls

### ISSUE THREAD

**Issue by ThomasLarg** [scrapy-plugins/scrapy-playwright#137]
Hello,

Is there a way to access the redirect_urls using scrapy-playwright.
I can see the redirections taking place using DEBUG but cannot seem
to access the list and associated status codes.

Thanks in advance.

**Comment by henribru** [comment]
In Scrapy this is usually handled by `RedirectMiddleware`, but I think the issue is that when using `scrapy-playwright`, the redirects happen internally inside Playwright and Scrapy never sees the intermediate requests and responses. I think the solution would be for `scrapy-playwright` to handle this itself and put the info in the meta in `_download_request_with_page`. It should be able to do this using https://playwright.dev/python/docs/api/class-request#request-redirected-from
