### ISSUE TITLE
Route

### ISSUE THREAD

**Issue by scrapenetwork** [scrapy-plugins/scrapy-playwright#139]
Wondering if there is a proper way to abort/close a page before it finishes loading, trying to use route but i cant seem to get it working

**Comment by elacuesta** [comment]
Not possible AFAICT. The scrapy way would probably be integrating with the `bytes/headers_received` signals (not currently being fired by this handler) but I'm having trouble thinking how that would be possible since it doesn't seem like Playwright exposes those events.

How are you using `route`? Just as a reminder, from the readme (docs about `playwright_page_init_callback`):
> scrapy-playwright uses Page.route & Page.unroute internally, please avoid using these methods unless you know exactly what you're doing.

**Comment by elacuesta** [comment]
Closing due to lack of feedback.

**Comment by mebs** [comment]
I also tried using `page.route` from the `playwright_page_init_callback`, but the reason it doesn't work is that Scrapy Playwright sets the `**` route _after_ invoking that init function. We can see [here](https://github.com/scrapy-plugins/scrapy-playwright/blob/6d01af20d1e8c0f8ef148e5a2e557bb0b9a9d02d/scrapy_playwright/handler.py#L276) that the page is created and initialized (that init callback is called in the page creation function), then the `**` route is set.

The order in which you set the routes in playwright is important, it seems that it will take the first one that matches the URL starting from the last route that was set and stop there.
You can try it in a simple "pure" playwright script.
```
# This
        await page.route("**", handle_any_route)
        await page.route("**/*.xml", handle_xml_route)

# is not the same as this
        await page.route("**/*.xml", handle_xml_route) # Handler never executed
        await page.route("**", handle_any_route)
```

So that part of the readme has me perplexed, you can't set routes even if you know what you're doing.
Am I missing something?
@elacuesta, would you object to calling `playwright_page_init_callback` _after_ the page is fully initialized (including setting the route)?
