### ISSUE TITLE
await page.content() may fail and then page not close

### ISSUE THREAD

**Issue by NiuBlibing** [scrapy-plugins/scrapy-playwright#165]
When [`await page.content()`](https://github.com/microsoft/playwright/issues/20483) failed with `playwright_include_page` set True, the function `_download_request_with_page` will break and then [`_download_request`](https://github.com/scrapy-plugins/scrapy-playwright/blob/b44d27fe64825828c8202238abd2d39aec76f97a/scrapy_playwright/handler.py#L295) will not close the page. I tried add [errorback](https://github.com/scrapy-plugins/scrapy-playwright#receiving-page-objects-in-callbacks), but  not work.

**Comment by elacuesta** [comment]
Exceptions here are [re-raised](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.25/scrapy_playwright/handler.py#L299) precisely to allow users to handle them in errbacks, and #91 was about adding the page early to Request.meta so that it can be closed manually. Please include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) showing how the errback is not working in your case.

**Comment by NiuBlibing** [comment]
Maybe a mistake,I can't reproduce it. `errback ` works well
