### ISSUE TITLE
json is not comma separated

### ISSUE THREAD

**Issue by iham** [scrapy-plugins/scrapy-playwright#185]
I want to export data from a website using playwright with scrapy (2.8.0)

this data is done via
```
def parse(self, response):
    ...
    yield {'field1':'foo', 'field2': 'bar'}
```

scrapy crawl myspider -o data.json
does:
```
[
{'field1':'foo', 'field2': 'bar'}
]
```

calling the same again and the json file gets extended by a new entry, but wrong:
```
[
{'field1':'foo', 'field2': 'bar'}
][
{'field1':'foo', 'field2': 'bar'}
]
```

1.) wrong, because its missing a colon in between items
2.) wrong, because it should extend the array, instead of creating a new one:
```
[
{'field1':'foo', 'field2': 'bar'}
,
{'field1':'foo', 'field2': 'bar'}
]
```

am I missing any params or is there an error/bug?

I also played with using item instead of yielding a dict, changed FEED params and so on - no effects on the output.

as I seek for a correct json output, I also don't want to use jsonline format.

hoping for help :)

**Comment by Gallaecio** [comment]
This is not something specific to Playwright, this is how Scrapy works.

Feed export, when appending to a file, can only append to the end of the file, they cannot edit the file. This restriction makes a lot of sense for technical reasons.

Ideally, you should use a format that works with this approach if you need to append to files. JSON Lines is the one Scrapy recommends.

Otherwise, rather than using Scrapy feed exports, you would need to implement your own, similar extension that follows the approach you want.
