### ISSUE TITLE
Question about how to work with the Fetch that is generated when visiting a page

### ISSUE THREAD

**Issue by diegocostares** [scrapy-plugins/scrapy-playwright#200]
I apologize if the question is a bit basic, but I haven't found a way to do it yet. Currently, I'm using the `should_abort_request` function to find a URL and headers of a Fetch request that returns a JSON containing the information I'm interested in.

 Is there a way to work with the response from that Fetch request with a Scrapy to save it in like item?

If I could I would try to directly access the url of this Fetch, however, this is encrypted and it changes depending on what I am looking for.

---

Example of what I'm currently doing (Not optimal, but will give an idea):
```python
def should_abort_request(req):
    if req.url.startswith("https://example-api.com/search?"):
        proses_req(req)
    return any(abort_conditions(req))


# This complicates all the flow by not being asynchronous
def proses_req(req):
    a = requests.get(
        req.url,
        headers=req.headers, # if I don't include it, it doesn't work
    )
    if a.status_code == 200:
        save_json(a.text)
 ```

**Comment by elacuesta** [comment]
This is not possible AFAIK, since Scrapy only allows to produce items from callbacks and if I understood correctly the response you're trying to intercept is not the final one so it's not handled by a callback.
As a workaround, perhaps you could [handle the `response` event](https://github.com/scrapy-plugins/scrapy-playwright#handling-page-events) and store the result of your processing in the spider object to be produced as an item later by the callback. It's not ideal, but at least you would eliminate the synchronous call. I haven't tested the code below but it might serve as an initial draft.

```python
class ResponseEventSpider(scrapy.Spider):
    name = "response_event"

    def start_requests(self):
        yield scrapy.Request(
            url="https://example.org",
            meta={
                "playwright": True,
                "playwright_page_event_handlers": {
                    "response": "handle_response",
                },
            },
        )

    def parse(self, response):
        for item in self.results.values():
            yield item

    async def handle_response(self, response):
        self.results[response.url] = {"url": response.url, "data": ...}
