### ISSUE TITLE
Playwright + Scrapy support for Scrapy Smart Proxy on Python

### ISSUE THREAD

**Issue by carlosplanchon** [scrapy-plugins/scrapy-playwright#210]
Hello, we work at a company where we are using in production a system that needs support for Scrapy Smart Proxy on Playwright + Scrapy.
I've seen that you can pass "proxies" on the context variable, but that option doesnt accept certificates as far as I know.

**Comment by elacuesta** [comment]
This looks much harder that I would have thought. I haven't tried anything myself, this is what I found:
* Chroumium: I found that ["Headless Chrome doesn't currently implement client certs."](https://bugs.chromium.org/p/chromium/issues/detail?id=1310715#c2), however the issue was closed with ["Could not repro this with new headless (--headless=new), everything works as expected."](https://bugs.chromium.org/p/chromium/issues/detail?id=1310715#c8); I'd recommend looking at the initial report for steps that might work.
* Firefox: [some people report](https://askubuntu.com/a/1360267) that is possible to use a custom certificate by defining it in the `policies.json` file ([Mozilla docs](https://github.com/mozilla/policy-templates/blob/master/README.md#policiesjson-15)), however it seems like it's not possible to specify such file with playwright according to [this comment](https://github.com/microsoft/playwright/issues/18115#issuecomment-1598800180) in upstream Playwright (the same comment also mentions persistent contexts, unfortunately I'm not sure exactly how they use them).

**Comment by carlosplanchon** [comment]
We managed to make it work.

**Comment by carlosplanchon** [comment]
Sure.
We added the corresponding certificate on our Dockerfile:

```
ADD zyte-ca.crt /usr/local/share/ca-certificates/zyte-ca.crt
RUN chmod 644 /usr/local/share/ca-certificates/zyte-ca.crt && update-ca-certificates
```

Then we enabled the proxy by this way:
```
Request(
    url="...",
    meta={
        "proxy": {
        "server": "https://proxy.zyte.com:8014/",
        "username": "..."
    },
    "playwright": True,
    "playwright_include_page": True,
}
```

As a suggerence, we also believe better docs are needed, and that it would greatly benefit Zyte clients by being an authoritative source on these matters, especially when dealing with new technologies like Playwright.

BTW, thx for your great work on this project.
