### ISSUE TITLE
How to use a proxies text file in scrapy-playwright

### ISSUE THREAD

**Issue by HistoriFy** [scrapy-plugins/scrapy-playwright#216]
Hi there again

I read the documentations in the README and even tried to google, bard, stack overflow, but couldnt find out how can I use a text file of proxies in scrapy-playwright

I have my text file in the following format `ip address: port`. Want to use few random proxies from it

```
5.161.107.192:8888
156.238.128.21:80
5.161.108.56:8888
5.161.109.67:8888
5.161.109.163:8888
.........
```

Any sort of support will be much appreciated, Apologies for any sort of inconvenience

**Comment by elacuesta** [comment]
There's no built-in support for this, you'll need to implement it yourself in your spider. In Playwright proxies are set either globally for the browser or per context, you'll probably want to create multiple contexts using different proxies. You can either create them at startup or during the crawl, see [this section in the README](https://github.com/scrapy-plugins/scrapy-playwright#browser-contexts) for instructions.
It might also be possible to use [scrapy-rotating-proxies](https://github.com/TeamHG-Memex/scrapy-rotating-proxies) and set your own downloader middleware after theirs so that the `process_request` method executes after `RotatingProxyMiddleware` (i.e. [configured with a highest number](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#activating-a-downloader-middleware)). That way you'll have a `proxy` meta key which you can use to set the context for the request, either an existing one of a new one to be created.

**Comment by HistoriFy** [comment]
Oh understood, my own downloader middleware works fine for my use case.

Would be nice if this feature is included in the future versions.

Thank you again @elacuesta . Please feel to close this issue! 🙏
