### ISSUE TITLE
Error after Updating

### ISSUE THREAD

**Issue by maciek85k** [scrapy-plugins/scrapy-playwright#220]
After updating Scrapy-playwright my spider does not work anymore. I get the following error and am unsure how to fix it.

``
Middleware.EXCEPTIONS_TO_RETRY += (PlaywrightTimeoutError,) 
``
``
AttributeError: can't set attribut
``

**Comment by elacuesta** [comment]
This is because of a change in Scrapy, see the changelog for the most recent version (2.10.0): https://docs.scrapy.org/en/latest/news.html#scrapy-2-10-0-2023-08-04.
![Screenshot 2023-08-15 at 10-25-42 Release notes — Scrapy 2 10 0 documentation](https://github.com/scrapy-plugins/scrapy-playwright/assets/1731933/e3c8038c-ccb2-41f0-a038-c538e6b36478)

See the docs for the upstream [`RETRY_EXCEPTIONS`](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#std-setting-RETRY_EXCEPTIONS) setting.

**Comment by maciek85k** [comment]
Thank you. 
However, I am not sure where and how to add the exception in the settings file. Can you help me out?
