### ISSUE TITLE
This is not an issue, rather it is a question regarding cookies

### ISSUE THREAD

**Issue by kmuente** [scrapy-plugins/scrapy-playwright#270]
With this framework how do I define a cookie in a yield request?
I ask because I don't see in the documentation how to do it.
Hoping not to disturb, I look forward to prompt responses.
Kind regards, Karlo Muente.

**Comment by elacuesta** [comment]
There are no specific docs about setting cookies because it's not different from regular Scrapy, just use the `cookies` [Request](https://docs.scrapy.org/en/2.11/topics/request-response.html#scrapy.http.Request) parameter.
Also, any way that you can set cookies for a Page or a Context in Playwright (for instance `Page.set_extra_http_headers`) also works here if you [request the retrieval of the page object](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#playwright_include_page).

See some relevant notes about headers in general at https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#playwright_process_request_headers
