### ISSUE TITLE
Optimising result with a full window

### ISSUE THREAD

**Issue by lime-n** [scrapy-plugins/scrapy-playwright#45]
I'm onwards trying to extract the last page number from a dynamic site. I've made my `xpaths` general, so that they can be used for dynamic loading. However! it returns `3`  when I yield the number. I know that my `xpath` is correct and it should be getting the page number.

My question is whether this is because a full-window is not implemented, and it somehow grabs the wrong number?

Here's what I have tried:

```
import scrapy
from scrapy_playwright.page import PageCoroutine
class JobSpider(scrapy.Spider):
    name = 'test_play'
    start_urls = ['https://jobsite.co.uk/jobs/Degree-Accounting-and-Finance']
    
    custom_settings = {
        'USER_AGENT':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15'
    }
    def start_requests(self):
        for url in self.start_urls:
            yield scrapy.Request(
                url = url,
                callback = self.parse,
                meta = dict(
                    playwright=True,
                    playwright_include_page = True,
                    playwright_page_coroutines = [
                        PageCoroutine('wait_for_selector', 'div.row.job-results-row')
                        ]
                        ))

    def parse(self, response):
        last_page = response.xpath('((//div)[position() mod 5=2]//div[@class]//a)[position() mod 65=53][last()]//text()').get()
        #last_page=int(last_page)
        #for page in range(2, last_page + 1):
        yield {
            'last_page':last_page
        }
```

Returns:
```
{'last_page': 3}
```

Here's a screenshot confirming I have the right path:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/jwqzO.png

**Comment by elacuesta** [comment]
IMHO that is an incorrect (and unnecessarily complex) xpath, and it probably works just as a coincidence for that particular case (perhaps the case in which there are 2 initial page links, an ellipsis, and a last page link; it's hard to say for sure though because the `mod`s probably cause it to depend on the amount of elements in the page).

Note that it doesn't work to get the last link in the general case:

![Screenshot at 2022-01-07 10-19-07](https://user-images.githubusercontent.com/1731933/148549976-626139bd-bbbd-4112-a9ad-5c97f5b9b6b1.png)

My suggestion would be to use a much more simple xpath, such as `//a[contains(@class, "PageLink-")][last()]`

**Comment by lime-n** [comment]
You're correct here! I actually had to zoom out a little on the webpage and change the xpath accordingly for it. This seemed to work
