### ISSUE TITLE
Can I use launch_persistent_context in scrapy-playwright ? 

### ISSUE THREAD

**Issue by anvaari** [scrapy-plugins/scrapy-playwright#52]
Hi there.
I'm new to scrapy-playwright .after I read whole doc and issues, I can't find option to [launch_persistent_context](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context). Is there any thing i missed or it's not support yet? 
Thanks

**Comment by elacuesta** [comment]
This is not supported at the moment.

Sounds interesting, but if I understand [the docs](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context) correctly, this would need some changes because it would not allow the creation of additional contexts:

> Launches browser that uses persistent storage located at user_data_dir and returns the only context. Closing this context will automatically close the browser.

The way I see it, it could involve a new setting (`PLAYWRIGHT_PERSISTENT_CONTEXT` or similar) which would disable `PLAYWRIGHT_CONTEXTS` (and the context-related Request.meta keys).

**Comment by anvaari** [comment]
Yes it would be great to use persistent context because some websites use multi factor authentication and only way to stay logged in is launch persistent context.
I agree with you about context. It create one context and don't allow multiple context.
