### ISSUE TITLE
[documentation needed] How to switch from python playwright to scrapy-playwright ? 

### ISSUE THREAD

**Issue by gikpro** [scrapy-plugins/scrapy-playwright#58]
What are the similarities of scrapy-playwright with the python version of playwright. What are the classes, functions of scrapy-playwright that correspond to those of playwright. Thanks !

**Comment by elacuesta** [comment]
scrapy-playwright is a Scrapy plugin (more specifically, a Scrapy Download handler), based on Playwright, which aims to bring browser capabilities into Scrapy. It tries to be as simple as possible, requiring only minimal changes in order to integrate it into an existing Scrapy project/spider. Please see the [Basic usage](https://github.com/scrapy-plugins/scrapy-playwright#basic-usage) section on the Readme, as well as the next sections for more advanced examples.
