### ISSUE TITLE
PLAYWRIGHT_ABORT_REQUEST does not accept lambdas as written in the documentation

### ISSUE THREAD

**Issue by AlvinSartorTrityum** [scrapy-plugins/scrapy-playwright#84]
In the documentation there is written that it is possible to pass a lambda in PLAYWRIGHT_ABORT_REQUEST like this:
`PLAYWRIGHT_ABORT_REQUEST = lambda req: req.resource_type == "image"`

In reality this is not possible, as the handler will always treat that value as a function path:
```
        self.abort_request: Optional[Callable[[PlaywrightRequest], bool]] = None
        if crawler.settings.get("PLAYWRIGHT_ABORT_REQUEST"):
            self.abort_request = load_object(crawler.settings["PLAYWRIGHT_ABORT_REQUEST"])
```

The code should check if `crawler.settings["PLAYWRIGHT_ABORT_REQUEST"]` contains a string and only in that case try to call `load_object` on it. Otherwise it should already contain the needed function.

**Comment by elacuesta** [comment]
The feature is tested using a `lambda` function: https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.14/tests/test_playwright_requests.py#L404 :wink: 

Since Scrapy 2.4.0, `load_object` will return any passed object unmodified if it's already a callable (https://github.com/scrapy/scrapy/pull/3873). I should probably clarify this restriction in the readme.

You did not include code or logs in your report, are you actually seeing exceptions? If so, are you maybe using an older version of Scrapy?

**Comment by elacuesta** [comment]
Closing due to lack of feedback
