### ISSUE TITLE
How to integrate Scrapy Playwright with Tor browser?

### ISSUE THREAD

**Issue by xxxDollbarBill** [scrapy-plugins/scrapy-playwright#89]
I have developed a project idea that I will be working on over the next few months. The idea will essentially integrate Tor over the scrapy playwright platform. Essentially, I want to use [playwrights keyboard](https://playwright.dev/docs/api/class-keyboard) functionality on Tor to get a new identity each time, to aid my privacy when scraping.

I have noticed that a new identity will close and re-open the browser, so I would also be interested to know what effects this has with scrapy playwright.

There is not any information online on how to make the integration possible, so I wanted to know from your professional experience, where would I have to begin with integrating the two?

**Comment by elacuesta** [comment]
I have no experience with Tor, I'm afraid I can't help you with that specifically.

At least with the current design, closing the browser would break things. I think it _might_ be possible to relaunch the browser, but you would need to wait for all pages to be done downloading things, otherwise you'd see a lot of `Target page, context or browser has been closed`. 

> I have noticed that a new identity will close and re-open the browser

It's not clear to me how this would happen in the context of an automated browser. What I mean is, would your application require access to the `Browser` instance in order to call `close` on it? Or would using the `page.keyboard` somehow trigger a call to the browser's `close` method? It might be possible to add a listener for the [`disconnected` event](https://playwright.dev/docs/api/class-browser#browser-event-disconnected) and launch a new browser there, but I don't know if that event is fired before or after closing the related contexts/pages.

**Comment by elacuesta** [comment]
Closing due to lack of feedback.
